#!/usr/bin/env bash
# A bash script that displays info about domains

# Function to display information about a subdomain
get_subdomain_info() {
    local domain="$1"
    local subdomain="$2"

    # Query DNS records for the specified subdomain
    local dns_info
    dns_info=$(dig +short "$subdomain.$domain")

    # Check if DNS query returned any result
    if [ -z "$dns_info" ]; then
        echo "Error: No DNS records found for $subdomain.$domain"
        return 1
    fi

    # Parse the DNS information and extract relevant details
    local record_type
    record_type=$(echo "$dns_info" | awk '{print $1}')
    local destination
    destination=$(echo "$dns_info" | awk '{print $2}')

    echo "The subdomain $subdomain is a $record_type record and points to $destination"
}

# Beginning of the main script
domain="$1"
subdomain="$2"

# If subdomain is not specified, display info for default subdomains
if [ -z "$subdomain" ]; then
    get_subdomain_info "$domain" "www"
    get_subdomain_info "$domain" "lb-01"
    get_subdomain_info "$domain" "web-01"
    get_subdomain_info "$domain" "web-02"

else
    # Display subdomain info
    get_subdomain_info "$domain" "$subdomain"
fi
