#!/bin/bash
# shellcheck disable=SC2086

get_subdomain_info() {
    local DOMAIN=$1
    local SUB=$2
    local FQDN="$SUB.$DOMAIN"

    INFO=$(dig $FQDN | grep -A1 'ANSWER SECTION:' | tail -n1)

    RECORD_TYPE=$(echo $INFO | awk '{print $4}')
    DESTINATION=$(echo $INFO | awk '{print $5}')

    echo "The subdomain $SUB is a $RECORD_TYPE record and points to $DESTINATION"
}

DOMAIN=$1
SUBDOMAIN=$2

if [ -n "$SUBDOMAIN" ]; then
    get_subdomain_info $DOMAIN $SUBDOMAIN
else
    for sub in www lb-01 web-01 web-02; do
        get_subdomain_info $DOMAIN $sub
    done
fi

