#!/usr/bin/env bash
# Create a script to install and configure HAProxy on lb-01 server
# Configure HAProxy to send traffic to web-01 and web-02 servers
# Make sure that HAProxy can be managed via an init script
# Install and configure HAproxy on the lb-01 server
sudo apt-get -y update
apt-get -y install haproxy

# edit config file
server_config=\
"
frontend  cobby-frontend
        bind *:80
        mode http
        default_backend cobby-backend

backend cobby-backend
        balance roundrobin
        server 495650-web-01 34.203.33.40 check
        server 495650-web-02 100.27.10.8 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable haproxy

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
