#!/usr/bin/env bash
# Install the required MySQL whose distribution must be 5.7.x
sudo wget -O mysql57 https://raw.githubusercontent.com/nuuxcode/alx-system_engineering-devops/master/scripts/mysql57 && sudo chmod +x mysql57 &&  sudo ./mysql57
