#!/usr/bin/env bash
# Description: Displays "To infinity and beyond indefinitely" with a 2-second sleep between iterations

trap 'echo I am invincible!!!' SIGTERM

while true; do
	echo "To infinity and beyond"
	sleep 2
done
