#!/usr/bin/env bash
# This script displays a story based on the content of /etc/passwd using a while loop + IFS

passwd_f="/etc/passwd"

while IFS=: read -r username _ userid groupid _ user_info home_dir shell; do
	command=$(basename "$shell")
	passcode="PASSWORD"

	echo "The user $username is part of the $groupid gang, lives in $home_dir, and rides $command."
	echo "USER ID's place is protected by the passcode $passcode, more info about the user here: $user_info"
	echo "-----------------------"
done < "$passwd_f"
