#!/usr/bin/env bash
# This script groups visitors by IP and HTTP status code and displays the data

log_file="apache-access.log"

awk '{ip_code=$1" "$9; count[ip_code]++} END{for (ic in count) print count[ic], ic}' "$log_file" | sort -nr
