#!/usr/bin/env bash
# This script displays "Best School" 10 times, showing "Hi" on the 9th iteration

cnt=1

while [ $cnt -le 10 ]; do
	if [ $cnt -eq 9 ]; then
		echo "Best School"
		echo "Hi"
	else
		echo "Best School"
	fi
	((cnt++))
done
