#!/usr/bin/env bash
# This script displays time for 12 hours and 59 minutes

time=0

while [ $time -le 12 ]; do
	echo "Hour: $time"

	min=1

	while [ $min -le 59 ]; do
		echo $min

		((min++))
	done

	((time++))
done | head -n 70
