#!/usr/bin/env bash
# This script provides information about the school file

f_path="school"

if [ -e "$f_path" ]; then
	echo "school file exists"

	if [ -s "$f_path" ]; then
		echo "school file is not empty"

		if [ -f "$f_path" ]; then
			echo "school is a regular file"
		else
		# File is not a regular file
			:
		fi
	else
		echo "school file is empty"
	fi
else
	echo "school file does not exist"
fi
