#!/usr/bin/env bash
# This script displays all active IPv4 IPs on the machine.

# Use ifconfig to retrieve active network interfaces and their IPs
ip -4 -o addr show | awk '{print $4}' | cut -d "/" -f 1
