#!/usr/bin/env bash
# This script configures Nginx to run as the nginx user and listen on port 8080

# Configure nginx
NGINX_CONF="/etc/nginx/nginx.conf"
DEFAULT_SITE="/etc/nginx/sites-available/default"

# Update nginx configuration
sed -i 's/#user www-data/user nginx;/' "$NGINX_CONF"

# Update nginx configuration to listen on port 8080 and run as nginx user
sed -i "s/80/8080/g" "$DEFAULT_SITE"

chmod 644 /etc/nginx/nginx.conf
pkill apache2

# Restart Nginx
sudo -u nginx service nginx start
