#!/usr/bin/env bash
# This script configures Nginx to run as the nginx user and listen on port 8080

# Configure nginx
chmod 644 /etc/nginx/nginx.conf

# Update nginx configuration
sed -Ei 's/\s*#?\s*user .*/user nginx;/' /etc/nginx/nginx.conf

# Update nginx configuration to listen on port 8080 and run as nginx user
sed -Ei 's/(listen (\[::\]:)?80) /\180 /' /etc/nginx/sites-enabled/default

chmod 644 /etc/nginx/nginx.conf
pkill apache2

# Restart Nginx
su nginx -s /bin/bash -c 'service nginx restart'
